//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public int Id { get; set; }
        public int IDpersona { get; set; }
        public string Pais { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
    
        public virtual Datos Datos { get; set; }
    }
}
